[package]
name = "ash-swapchain"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { path = "../ash", version = "0.34" }

[dev-dependencies]
winit = "0.26"
ash-window = { path = "../ash-window", version = "0.8" }
