use super::definitions::*;
#[doc = "Provided by VK_VERSION_1_0"]
pub const MAX_PHYSICAL_DEVICE_NAME_SIZE: usize = 256;
#[doc = "Provided by VK_VERSION_1_0"]
pub const UUID_SIZE: usize = 16;
#[doc = "Provided by VK_VERSION_1_1"]
pub const LUID_SIZE: usize = 8;
#[doc = "Provided by VK_VERSION_1_0"]
pub const MAX_EXTENSION_NAME_SIZE: usize = 256;
#[doc = "Provided by VK_VERSION_1_0"]
pub const MAX_DESCRIPTION_SIZE: usize = 256;
#[doc = "Provided by VK_VERSION_1_0"]
pub const MAX_MEMORY_TYPES: usize = 32;
#[doc = "The maximum number of unique memory heaps, each of which supporting 1 or more memory types"]
#[doc = ""]
#[doc = "Provided by VK_VERSION_1_0"]
pub const MAX_MEMORY_HEAPS: usize = 16;
#[doc = "Provided by VK_VERSION_1_0"]
pub const LOD_CLAMP_NONE: f32 = 1000.00;
#[doc = "Provided by VK_VERSION_1_0"]
pub const REMAINING_MIP_LEVELS: u32 = !0;
#[doc = "Provided by VK_VERSION_1_0"]
pub const REMAINING_ARRAY_LAYERS: u32 = !0;
#[doc = "Provided by VK_EXT_image_sliced_view_of_3d"]
pub const REMAINING_3D_SLICES_EXT: u32 = !0;
#[doc = "Provided by VK_VERSION_1_0"]
pub const WHOLE_SIZE: u64 = !0;
#[doc = "Provided by VK_VERSION_1_0"]
pub const ATTACHMENT_UNUSED: u32 = !0;
#[doc = "Provided by VK_VERSION_1_0"]
pub const TRUE: Bool32 = 1;
#[doc = "Provided by VK_VERSION_1_0"]
pub const FALSE: Bool32 = 0;
#[doc = "Provided by VK_VERSION_1_0"]
pub const QUEUE_FAMILY_IGNORED: u32 = !0;
#[doc = "Provided by VK_VERSION_1_1"]
pub const QUEUE_FAMILY_EXTERNAL: u32 = !1;
#[doc = "Provided by VK_EXT_queue_family_foreign"]
pub const QUEUE_FAMILY_FOREIGN_EXT: u32 = !2;
#[doc = "Provided by VK_VERSION_1_0"]
pub const SUBPASS_EXTERNAL: u32 = !0;
#[doc = "Provided by VK_VERSION_1_1"]
pub const MAX_DEVICE_GROUP_SIZE: usize = 32;
#[doc = "Provided by VK_VERSION_1_2"]
pub const MAX_DRIVER_NAME_SIZE: usize = 256;
#[doc = "Provided by VK_VERSION_1_2"]
pub const MAX_DRIVER_INFO_SIZE: usize = 256;
#[doc = "Provided by VK_KHR_ray_tracing_pipeline"]
pub const SHADER_UNUSED_KHR: u32 = !0;
#[doc = "Provided by VK_KHR_global_priority"]
pub const MAX_GLOBAL_PRIORITY_SIZE_KHR: usize = 16;
#[doc = "Provided by VK_EXT_shader_module_identifier"]
pub const MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT: usize = 32;
#[doc = "Provided by VK_KHR_pipeline_binary"]
pub const MAX_PIPELINE_BINARY_KEY_SIZE_KHR: usize = 32;
#[doc = "Provided by VK_KHR_video_decode_av1"]
pub const MAX_VIDEO_AV1_REFERENCES_PER_FRAME_KHR: usize = 7;
#[doc = "Provided by VK_AMDX_shader_enqueue"]
#[cfg(feature = "provisional")]
pub const SHADER_INDEX_UNUSED_AMDX: u32 = !0;
pub const SHADER_UNUSED_NV: u32 = SHADER_UNUSED_KHR;
